# Generated by Django 4.0 on 2023-08-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TJ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='photo_album',
        ),
    ]
