# Generated by Django 4.2.3 on 2023-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TJ', '0003_remove_journal_entries_remove_user_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
